/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.timmhirsens.azureblobcache;

import org.gradle.api.Plugin;
import org.gradle.api.initialization.Settings;
import org.gradle.caching.configuration.BuildCacheConfiguration;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class AzureBlobBuildCachePlugin implements Plugin<Settings> {

	private static final Logger LOGGER = LoggerFactory.getLogger(AzureBlobBuildCachePlugin.class);

	@Override
	public void apply(Settings settings) {
		LOGGER.info("Registering Azure-Blob-Storage build cache");
		BuildCacheConfiguration buildCacheConfiguration = settings.getBuildCache();
		buildCacheConfiguration.registerBuildCacheService(AzureBlobStorageBuildCache.class, AzureBlobStorageBuildCacheServiceFactory.class);
	}
}
