/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.timmhirsens.azureblobcache;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple unit test for the 'de.timmhirses.azureblobcache.greeting' plugin.
 */
public class AzureblobBuildCachePluginTest {
    @Test public void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
    }
}
